"""empty message

Revision ID: 114509283562
Revises: 64af1f0ce2ed
Create Date: 2025-07-22 15:40:59.628136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '114509283562'
down_revision = '64af1f0ce2ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('april_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('family', sa.String(length=16), nullable=False),
    sa.Column('tag_size', sa.Float(), nullable=False),
    sa.Column('detector_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['detector_id'], ['april_tag_detector.id'], ),
    sa.PrimaryKeyConstraint('id', 'tag_id')
    )
    with op.batch_alter_table('april_tag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_april_tag_tag_id'), ['tag_id'], unique=False)

    with op.batch_alter_table('april_tag_detector', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_tag_size', sa.Float(), nullable=False, server_default='0.1016'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('april_tag_detector', schema=None) as batch_op:
        batch_op.drop_column('default_tag_size')

    with op.batch_alter_table('april_tag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_april_tag_tag_id'))

    op.drop_table('april_tag')
    # ### end Alembic commands ###
