"""empty message

Revision ID: 64af1f0ce2ed
Revises: 
Create Date: 2025-07-20 20:34:40.226723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64af1f0ce2ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cv_undistortable_camera', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calib_res_width', sa.Integer(), nullable=False, server_default='640'))
        batch_op.add_column(sa.Column('calib_res_height', sa.Integer(), nullable=False, server_default='480'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cv_undistortable_camera', schema=None) as batch_op:
        batch_op.drop_column('calib_res_height')
        batch_op.drop_column('calib_res_width')

    # ### end Alembic commands ###
