"""empty message

Revision ID: e3f06e135c61
Revises: 
Create Date: 2025-07-25 21:56:25.657291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3f06e135c61'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('april_tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ensure_static', sa.Boolean(), nullable=False, server_default='False'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('april_tag', schema=None) as batch_op:
        batch_op.drop_column('ensure_static')

    # ### end Alembic commands ###
